-- 코드를 입력하세요
WITH T1 AS (
    SELECT
        CAR_ID,
        COUNT(*) AS TOTAL
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY
        CAR_ID
    HAVING
        COUNT(*) >= 5
)
SELECT
    MONTH(c.START_DATE) AS `MONTH`,
    t.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
JOIN T1 t
  ON t.CAR_ID = c.CAR_ID
WHERE c.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY
    MONTH(c.START_DATE),
    t.CAR_ID
ORDER BY
    `MONTH`,
    CAR_ID DESC;