-- 코드를 작성해주세요
SELECT
    c.ITEM_ID,
    c.ITEM_NAME,
    c.RARITY
FROM ITEM_INFO p
JOIN ITEM_TREE t
    ON p.ITEM_ID = t.PARENT_ITEM_ID
JOIN ITEM_INFO c
    ON t.ITEM_ID = c.ITEM_ID
WHERE p.RARITY = 'RARE'
ORDER BY
    ITEM_ID DESC;