-- 코드를 입력하세요
WITH TOTAL_TABLE AS (
    SELECT
        f.SHIPMENT_ID as SHIPMENT_ID,
        f.FLAVOR as FLAVOR,
        f.TOTAL_ORDER as TOTAL_ORDER,
        i.INGREDIENT_TYPE as INGREDIENT_TYPE
    FROM FIRST_HALF f
    JOIN ICECREAM_INFO i ON i.FLAVOR = f.FLAVOR
)
SELECT
    FLAVOR
FROM TOTAL_TABLE
WHERE INGREDIENT_TYPE = 'fruit_based'
  AND TOTAL_ORDER >= 3000
ORDER BY
    TOTAL_ORDER DESC;