-- 코드를 작성해주세요
WITH T1 AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS `YEAR`,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY
        YEAR
)
SELECT
    YEAR(e.DIFFERENTIATION_DATE) AS `YEAR`,
    (t.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM ECOLI_DATA e
JOIN T1 t
  ON YEAR(e.DIFFERENTIATION_DATE) = t.YEAR
ORDER BY
    `YEAR`, YEAR_DEV;