-- 코드를 입력하세요
WITH T1 AS (
    SELECT
        HISTORY_ID,
        CAR_ID,
        '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)
SELECT
    DISTINCT(c.CAR_ID) AS CAR_ID,
    IFNULL(t.AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
LEFT JOIN T1 t
  ON c.CAR_ID = t.CAR_ID
ORDER BY
    CAR_ID DESC;