-- 코드를 입력하세요
WITH T1 AS (
    SELECT
        b.BOARD_ID,
        b.WRITER_ID AS BOARD_WRITER_ID,
        b.TITLE,
        b.CONTENTS AS BOARD_CONTENTS,
        b.PRICE,
        b.CREATED_DATE AS BOARD_CREATED_DATE,
        b.STATUS,
        b.VIEWS,
        r.REPLY_ID,
        r.WRITER_ID AS REPLY_WRITER_ID,
        r.CONTENTS AS REPLY_CONTENTS,
        r.CREATED_DATE AS REPLY_CREATED_DATE
    FROM USED_GOODS_BOARD b
    JOIN USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
)   
SELECT
    TITLE,
    BOARD_ID,
    REPLY_ID,
    REPLY_WRITER_ID AS WRITER_ID,
    REPLY_CONTENTS AS CONTENTS,
    DATE_FORMAT(REPLY_CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM T1
WHERE YEAR(BOARD_CREATED_DATE) = 2022
  AND MONTH(BOARD_CREATED_DATE) = 10
ORDER BY
    REPLY_CREATED_DATE,
    TITLE;