-- 코드를 입력하세요
WITH T1 AS (
    SELECT
        FOOD_TYPE,
        REST_ID,
        REST_NAME,
        FAVORITES,
        RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS `RANK`
    FROM REST_INFO
)
SELECT
    FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM T1
WHERE `RANK` = 1
ORDER BY
    FOOD_TYPE DESC;